name: buildactions

on:
  push:
    branches: main

  jobs:
    build:
      runs-on: windows
        steps:
          -  uses: actions/checkout@v4.2.2

          -name : run a sample
            run: echo hello word
          
