name: buildactions

on:
  push:
    branches: main
   
  workflow_dispatch:

jobs:
  build:
    runs-on: SANTOSHP-LAPTOP
    steps:
        -  uses: actions/checkout@v4.2.2

        - name: run a sample
          run: echo hello word
    
          
